### ISSUE TITLE
Possible to set up my own CDN for older clients?

### ISSUE THREAD

**Issue by SyntaxHell** [trinity6/trinity6.github.io#51]
Since WoD 6.2.3 20779 isn't supported any longer and need to contact a CDN to open the clients, I was wondering how I can setup my own for me and my friends?

Like, do I just choose a local path like "C:\" in the connection patcher and put the version file there for all clients? Or do I have to setup a webserver for this to work?

All I want is to play it offline, or with my friends on offline LAN.

I really appriciate all help I can get with this!

**Comment by SyntaxHell** [comment]
Managed to figure this out!

**Comment by funjoker** [comment]
Yes it's possible.
Since the the official casc does not support any older patches you need to have a backup of the casc system. (Rip of the the cdn)

[https://bnet.marlam.in/](url)

This is where you go.

Download the CDN files you need, set up a server.
And then patch you CDN Server in your client. (how to do that you can see a closes PR of mine at TrinityCore)

**Comment by SyntaxHell** [comment]
Thanks! This will come in handy!

Seems like the 6.2.3 client only needed to have the cdn and version file. I managed to fix this myself by ripping them of another website and redirecting the DNS to localhost for my own Appache server to run from.

Could you link me the resolved case? I mean, it wouldn't hurt to skip the webserver for the client to run!

**Comment by funjoker** [comment]
> Seems like the 6.2.3 client only needed to have the cdn and version file.

Nope, it needs the whole hashed files from the CDN.
If its works without these, sounds like you are using some kinda stuff of some sort of pserver.
